name: plugin-postgres-container
description: Postgres localmente com docker e docker-compose
display-name: plugin-postgres-container
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Usuario do banco de dados
    type: text
    name: usuario
    default: usuario
  - label: Senha do banco de dados
    type: text
    name: senha
    default: "123@abc"
  - label: Porta padrao do banco de dados
    type: text
    name: porta
    default: 5433
  - label: Nome do banco de dados
    type: text
    name: banco_dados
    default: meu_banco_dados
