schema-version: v2
kind: plugin
metadata:
  name: spring-base
  display-name: spring-base
  description: Plugin base para uma aplicação com java e spring-boot
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - java
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Java
    - Maven
    - Springboot
  inputs:
    - label: Nome do projeto
      type: text
      name: nome_projeto
      default: nomeProjeto
    - label: Descricao
      type: text
      name: descricao
      required: true
    - label: Group id
      type: text
      name: group_id
      default: br.com.dominio
    - label: Artifact
      type: text
      name: artifact
      default: projeto
  computed-inputs:
    pacote_base: "{{group_id}}.{{nome_projeto}}"
    pastas: "{{computed_inputs.pacote_base | replace('.','/')}}"
