name: "create-plugin"
description: Just a simple Template
type: scaffold
haveSample: false
programmatic: false
tags:
  - "create-plugin-scaffold"
inputs:

  # parameters always provided by stk create plugin/template
  - label: "entity"
    type: text
    default: plugin
    name: entity
  
  - label: "name"
    type: text
    name: "plugin_name"
  
  # parameters will be asked if not provided by stk create plugin/template options
  - label: "Plugin description:"
    type: text
    name: "plugin_description"
    default: "Describe your plugin explaining its purpose"
    condition:
      variable: "entity"
      operator: "=="
      value: "plugin"

  - label: "Template description:"
    type: text
    name: "plugin_description"
    default: "Describe your template explaining its purpose"
    condition:
      variable: "entity"
      operator: "=="
      value: "template"

hooks:
  - type: render-templates
    trigger: after-render
    path: plugin-templates
    condition:
      variable: entity
      operator: ==
      value: plugin