schema-version: v2
kind: plugin
metadata:
  name: plugin-postgres-container
  display-name: plugin-postgres-container
  description: adiciona docker-compose com postgres 
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - java
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  inputs:
  - label: Usuario do banco de dados
    type: text
    name: usuario
    default: usuario
  - label: Senha do banco de dados
    type: text
    name: senha
    default: "123@abc"
  - label: Porta padrao do banco de dados
    type: text
    name: porta
    default: 5433
  - label: Nome do banco de dados
    type: text
    name: banco_dados
    default: meu_banco_dados